from __future__ import annotations

import copy
import json
from pathlib import Path

from body_reader import enrich_article_bodies
from fa_editor import editorial_meta
from fa_narrative import build_narrative, source_chunks
from translate_fa import PersianTranslator, compact_words, looks_persian

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "news.json"
NARRATIVE_VERSION = 1


def translate_narrative(translator: PersianTranslator, source: str, title_fa: str = "") -> tuple[str, str]:
    """Translate fact-dense source chunks separately, then rebuild readable Persian prose."""
    translated: list[str] = []
    for chunk in source_chunks(source):
        translated.append(translator.translate(chunk, 430))
    return build_narrative(translated, title_fa=title_fa)


def _previous_snapshot(items: list[dict]) -> dict[str, dict]:
    """Build a cache view while forcing legacy deep reports through narrative backfill."""
    result: dict[str, dict] = {}
    for item in items:
        item_id = item.get("id")
        if not item_id:
            continue
        previous = copy.deepcopy(item)
        if (
            previous.get("narrative_fa")
            and previous.get("report_coverage") == "بر پایه بدنه مقاله"
        ):
            previous.setdefault("article_body", {"status": "extracted", "cached_from_narrative": True})
            previous["report_source_kind"] = "article_body"
        else:
            # Older article-body reports were generated by the previous translation
            # pipeline. Remove their body-cache markers from this in-memory snapshot
            # so the reader fetches the source again and replaces them with narrative_fa.
            previous.pop("article_body", None)
            previous.pop("report_source_kind", None)
            previous.pop("report_source_chars", None)
            previous.pop("report_selected_chars", None)
        result[item_id] = previous
    return result


def main() -> None:
    if not DATA_PATH.exists():
        raise SystemExit("news.json does not exist")

    payload = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    items = payload.get("items", [])
    previous_by_id = _previous_snapshot(items)

    stats = enrich_article_bodies(items, previous_by_id)
    translator = PersianTranslator(timeout=5, pause=0.05)
    narrative_upgraded = 0
    narrative_failed = 0

    for item in items:
        source = item.pop("_report_source", "")
        if not source or item.get("report_source_kind") != "article_body":
            continue

        # Do not rewrite Persian publishers' prose as if it were our own narrative.
        # Their feed summary remains the public Persian fallback.
        if item.get("language") == "fa" or looks_persian(item.get("title", "")):
            item["report_basis"] = "feed-summary"
            item["editorial"] = editorial_meta("source-fa-normalized")
            continue

        try:
            narrative, summary = translate_narrative(
                translator,
                source,
                title_fa=str(item.get("title_fa") or ""),
            )
            if narrative:
                item["narrative_fa"] = narrative
                item["report_fa"] = narrative
                item["summary_fa"] = compact_words(summary or narrative, 95)
                item["report_coverage"] = "بر پایه بدنه مقاله"
                item["report_basis"] = "article-body-narrative"
                item["narrative_basis"] = "fact-dense article-body selection"
                item["narrative_version"] = NARRATIVE_VERSION
                item["narrative_word_count"] = len(narrative.replace("\n", " ").split())
                item["report_word_count"] = item["narrative_word_count"]
                item["editorial"] = editorial_meta("narrative-body")
                narrative_upgraded += 1
        except Exception as exc:
            item["narrative_error"] = str(exc)[:160]
            narrative_failed += 1

    payload["schema_version"] = "0.17"
    payload["article_body_stats"] = {
        "attempted": stats.attempted,
        "extracted": stats.extracted,
        "blocked": stats.blocked,
        "short": stats.short,
        "failed": stats.failed,
        "reused": stats.reused,
        "queued": stats.queued,
        "narratives_upgraded": narrative_upgraded,
        "narrative_translation_failed": narrative_failed,
    }
    DATA_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(
        "Article body reader: "
        f"{stats.attempted} attempted; {stats.extracted} extracted; {stats.blocked} blocked; "
        f"{stats.short} short; {stats.failed} failed; {stats.reused} reused; {stats.queued} queued."
    )
    print(
        "Persian narratives: "
        f"{narrative_upgraded} upgraded from article bodies; {narrative_failed} translation failures."
    )


if __name__ == "__main__":
    main()
