FI.bindTheme();
const $=id=>document.getElementById(id);
const id=FI.params().get('id');
const DAY=864e5;
const FOLLOW_KEY='fi_followed_brands_v1';
const LENSES={
  all:{label:'همه'},
  ai:{label:'AI و فناوری',terms:['ai','artificial intelligence','automation','technology','digital','robot','هوش مصنوعی','اتوماسیون','فناوری','ربات'],cats:['restaurant_technology_ai','equipment_automation']},
  management:{label:'مدیریت و استراتژی',terms:['strategy','leadership','management','growth','expansion','franchise','استراتژی','مدیریت','توسعه','فرنچایز'],cats:['franchising','restaurant_industry']},
  operations:{label:'عملیات',terms:['operations','labor','kitchen','supply chain','food safety','عملیات','نیروی انسانی','آشپزخانه','زنجیره تأمین','ایمنی غذا'],cats:['restaurant_operations','labor_management','supply_chain','food_safety']},
  product:{label:'محصول',terms:['product','menu','innovation','launch','beverage','ingredient','محصول','منو','نوآوری','نوشیدنی','مواد اولیه'],cats:['menu_product_innovation','beverage','ingredients_rd','food_manufacturing']},
  marketing:{label:'مارکتینگ و مشتری',terms:['marketing','brand','consumer','customer','loyalty','campaign','pricing','بازاریابی','برند','مشتری','وفاداری','کمپین','قیمت'],cats:['marketing_branding','consumer_behavior','food_cost_pricing']},
  finance:{label:'مالی',terms:['revenue','sales','profit','earnings','investment','roi','فروش','درآمد','سود','سرمایه'],cats:['food_cost_pricing']}
};
function followedSet(){try{return new Set(JSON.parse(localStorage.getItem(FOLLOW_KEY)||'[]'))}catch{return new Set()}}
function saveFollow(set){localStorage.setItem(FOLLOW_KEY,JSON.stringify([...set]))}
function isFollowing(){return followedSet().has(id)}
function toggleFollow(){const set=followedSet();set.has(id)?set.delete(id):set.add(id);saveFollow(set);const btn=$('brandFollow');if(btn){btn.textContent=set.has(id)?'✓ دنبال می‌کنم':'+ دنبال کردن برند';btn.classList.toggle('active',set.has(id))}}
window.toggleBrandFollow=toggleFollow;
function brandFrom(items){const c=FI.brandCatalogById?.[id];if(c)return c;for(const item of items){const b=(item.brands||[]).find(x=>x.id===id);if(b)return {id:b.id,name:b.name||b.id,fa:b.fa||b.name||b.id,market:b.market||((item.market==='iran'||(item.iran_relevance_score||0)>=70)?'iran':'world'),sector:'سایر'}}return null}
function logoHtml(b){const logo=FI.brandLogo?FI.brandLogo(b):'';return logo?`<img class="brand-avatar" src="${FI.esc(logo)}" alt="" referrerpolicy="no-referrer" onerror="this.style.display='none'">`:`<div class="brand-avatar" style="display:grid;place-items:center;font-family:Estedad">${FI.esc((b.fa||b.name||'?').slice(0,1))}</div>`}
function sourceName(x){return x.discovered_publisher||x.source?.name||'منبع'}
function timelineItem(x){const watched=(x.brand_watch?.matched_brand_ids||[]).includes(id);const official=x.source?.class==='official_brand_channel';const summary=String(x.recap_fa||x.summary_fa||'').trim();return `<a class="timeline-item" href="story.html?id=${encodeURIComponent(x.id)}"><div class="timeline-meta"><span>${FI.esc(sourceName(x))}</span><span>•</span><span>${FI.ago(x.published_at)}</span>${watched?'<span class="signal-badge">Brand Watch</span>':''}${official?'<span class="official-badge">منبع رسمی برند</span>':''}</div><h3>${FI.richText(x.title_fa||x.title||'')}</h3>${summary?`<p>${FI.richText(summary.slice(0,260))}${summary.length>260?'…':''}</p>`:''}</a>`}
function topTopics(rows){const counts=new Map();rows.forEach(x=>(x.categories||[]).forEach(c=>counts.set(c,(counts.get(c)||0)+1)));return [...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)}
function matchesLens(x,lens){if(lens==='all')return true;const rule=LENSES[lens];if(!rule)return true;if((x.categories||[]).some(c=>(rule.cats||[]).includes(c)))return true;const hay=[x.title,x.title_fa,x.summary,x.summary_fa,x.recap_fa,...(x.topics||[])].join(' ').toLowerCase();return (rule.terms||[]).some(t=>hay.includes(t.toLowerCase()))}
function lensCounts(rows){return Object.fromEntries(Object.keys(LENSES).map(k=>[k,rows.filter(x=>matchesLens(x,k)).length]))}

fetch('data/news.json',{cache:'no-store'}).then(r=>r.json()).then(data=>{
  const items=data.items||[];const brand=brandFrom(items);if(!brand){$('brandApp').innerHTML='<div class="empty-brand">این برند در کاتالوگ پیدا نشد.</div>';return}
  const rows=items.filter(x=>x.title_fa&&(x.brands||[]).some(b=>b.id===id)).sort((a,b)=>new Date(b.published_at)-new Date(a.published_at));
  const now=Date.now(),d30=rows.filter(x=>now-new Date(x.published_at)<30*DAY).length,d7=rows.filter(x=>now-new Date(x.published_at)<7*DAY).length,watch=rows.filter(x=>(x.brand_watch?.matched_brand_ids||[]).includes(id)).length,official=rows.filter(x=>x.source?.class==='official_brand_channel').length;
  const links=FI.brandLinksFor?FI.brandLinksFor(brand):[],topics=topTopics(rows),market=brand.market==='iran'?'🇮🇷 ایران':'🌍 جهان',following=isFollowing(),counts=lensCounts(rows);
  document.title=`${brand.fa||brand.name} | رادار برندها`;
  $('brandApp').className='brand-profile-layout';
  $('brandApp').innerHTML=`<section class="brand-profile-main"><div class="brand-hero"><div class="brand-profile-header">${logoHtml(brand)}<div><h1>${FI.esc(brand.fa||brand.name)}</h1><p>${FI.esc(brand.name||'')} · ${market} · ${FI.esc(brand.sector||'صنعت غذا')}</p></div></div><div class="brand-tags"><span class="brand-tag watch">● تحت رصد Brand Watch</span><span class="brand-tag">${FI.esc(brand.sector||'صنعت غذا')}</span><button id="brandFollow" class="pill-btn ${following?'active':''}" onclick="toggleBrandFollow()">${following?'✓ دنبال می‌کنم':'+ دنبال کردن برند'}</button></div></div><div class="brand-kpis"><div class="brand-kpi"><b>${FI.faN(d30)}</b><span>خبر در ۳۰ روز</span></div><div class="brand-kpi"><b>${FI.faN(d7)}</b><span>خبر در ۷ روز</span></div><div class="brand-kpi"><b>${FI.faN(watch)}</b><span>سیگنال رصد اختصاصی</span></div><div class="brand-kpi"><b>${FI.faN(official)}</b><span>فعالیت از منبع رسمی</span></div></div><div class="brand-hero"><h1 style="font-size:18px">تایم‌لاین برند</h1><p>از یک زاویه مشخص وارد شو؛ مثلاً فقط ببین ${FI.esc(brand.fa||brand.name)} درباره AI، عملیات یا محصول چه کرده است.</p><div id="brandLensBar" class="brand-lens-bar">${Object.entries(LENSES).map(([key,rule])=>`<button data-lens="${key}" class="brand-lens ${key==='all'?'active':''}">${rule.label}<small>${FI.faN(counts[key])}</small></button>`).join('')}</div></div><div id="brandTimeline" class="timeline"></div></section><aside class="brand-profile-side"><div class="brand-side-card"><h3>وب‌سایت و شبکه‌های رسمی</h3><div class="brand-side-links">${links.map(x=>`<a href="${FI.esc(x.url)}" target="_blank" rel="noopener noreferrer nofollow"><span>${x.icon} ${FI.esc(x.label)}</span><small>${x.direct?'رسمی':'جست‌وجو'}</small></a>`).join('')}</div></div><div class="brand-side-card"><h3>موضوع‌های پرتکرار</h3>${topics.length?topics.map(([topic,count])=>`<div class="mini-stat"><span>${FI.esc(FI.categoryFa?.[topic]||FI.labels?.[topic]||topic)}</span><b>${FI.faN(count)}</b></div>`).join(''):'<p style="color:var(--muted);font-size:11px">هنوز داده کافی نداریم.</p>'}</div><div class="brand-side-card"><h3>دسترسی سریع</h3><div class="brand-actions"><a class="pill-btn" href="${brand.market==='iran'?'iran.html':'explore.html'}?brand=${encodeURIComponent(id)}#feed">فید خبرهای برند</a><a class="pill-btn" href="brands.html?market=${brand.market==='iran'?'iran':'world'}">برندهای ${brand.market==='iran'?'ایران':'جهان'}</a></div></div></aside>`;
  function renderTimeline(lens='all'){const filtered=rows.filter(x=>matchesLens(x,lens));$('brandTimeline').innerHTML=filtered.length?filtered.slice(0,60).map(timelineItem).join(''):`<div class="empty-brand">برای این زاویه هنوز خبر معناداری ثبت نشده است.</div>`;$('brandLensBar').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.lens===lens))}
  $('brandLensBar').querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>renderTimeline(btn.dataset.lens)));
  renderTimeline();
}).catch(err=>{$('brandApp').innerHTML=`<div class="empty-brand">خطا در دریافت داده برند: ${FI.esc(err.message||err)}</div>`});
